// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("plumlore")>]
[<assembly: AssemblyProductAttribute("plumlore")>]
[<assembly: AssemblyDescriptionAttribute("Library for formal concept analysis")>]
[<assembly: AssemblyVersionAttribute("0.1.0")>]
[<assembly: AssemblyFileVersionAttribute("0.1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "plumlore"
    let [<Literal>] AssemblyProduct = "plumlore"
    let [<Literal>] AssemblyDescription = "Library for formal concept analysis"
    let [<Literal>] AssemblyVersion = "0.1.0"
    let [<Literal>] AssemblyFileVersion = "0.1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
